### ISSUE TITLE
responds to all?

### ISSUE THREAD

**Issue by xblox** [dark81/koa-json-rpc2#1]
hi,
thanks a lot but something is really wrong. my koa app has many routes and your module package responds to all requests ? It doesn't even check for method being GET or POST. Am I missing something ? 

g

**Comment by dark81** [comment]
Hi,

I suppose to use koa-mount module to add separate entry point for json-rpc.

For instance:

```javascript

const koa = require('koa');
const mount = require('koa-mount');
const koaJsonRpc2 = require('koa-json-rpc2');

// Create koa application to handle RPC queries
const rpcApp = koa();
// Create top level koa application
const app = koa();

// Create rpc router instance
const jrpc2 = koaJsonRpc2();

// Register new rpc function
jrpc2.use('user', function* user() {
  return 'root'
});

// Register rpc router as koa middleware
rpcApp.use(jrpc2.app());
// Register entry point for RPC
app.use(mount('/api', rpcApp));
// Listen for user queries
app.listen(3000);
```

**Comment by xblox** [comment]
fantastic, thanks a lot !

**Comment by xblox** [comment]
hi, i ported your impl. to Typescript [here](https://github.com/xblox/server-core-ts/tree/master/src/rpc). Grab a copy, not sure how long the repo will be there...

**Comment by dark81** [comment]
Thank you!
